### PR TITLE
Release 1.0: Budgetify - The Budget App

### PR DESCRIPTION
**Pull request by Anjacodes**
In this milestone, I:

* Followed the [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=).
* Gave appropriate credit to the author [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) in the README of my project.
* Created a simple page with the name of my app (Budgetify), and links to the sign-up and log-in pages.
* Made sure that the user is able to register in the app with name, email, and password (all mandatory), and they can't access pages that require the user to be logged in.
* Implemented the following functionality:
        - When the user logs in, they are presented with the categories page.
        - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
        - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
        - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
        - For a given category, the list of transactions is presented, ordered by the most recent.
        - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
        - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
        - When the user clicks on the "Back" button (<), the user navigates to the home page.
        - The user can fill out a form to create a new category, indicating their name and icon (both mandatory).
        - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
        - When the user clicks on the "Back" button (<), the user navigates to the home page.
        - The user can fill out a form to create a new transaction with:
            name (mandatory)
            amount (mandatory)
            categories (mandatory at least one)
        - The user clicks (or taps) the "Save" button to create the new category, and is taken to the transactions page for that category.
        - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

* Created unit and integration tests for all the most important components of my RoR application.
* Used Postgres as my database.
* Used devise for authentication.
* Validate all user input to make sure that anyone with bad intentions cannot compromise my app.
* Deployed the project online, click [here](https://boiling-falls-90821.herokuapp.com/users/sign_in) to see

* Find a video of me presenting the project [here](https://www.loom.com/share/2af14f57a5934e0598ff7f05da54b0dd).

### CODE REVIEW

**Comment by GzimAsani** [comment]
Hi @Anjacodes   ,
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Your code organization is good.
 
 ## Required Changes 
## Because of the high volume of changes(Over 5000) it is impossible for me to give a review using the `files changes`. This is the reason why I have not used inline comments. 
 * [x] For each category, the list of transactions should be presented and ordered by the most recent
 * [x] At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category)
 * [x] When I try to signup but I do not provide all the necessary information as expected I cannot create a user, but there is no flash message to let me know what is going wrong. Please add that, in order to explain to the user what are they missing
 * [x] When I try to log in and I provide the wrong credentials, I should see a validation message telling me that I have provided the wrong credentials.
 * [x] You have some tests failing, kindly  fix them Screenshot from 2022-04-20 18-15-30




 _Check the comments under the review._
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Anjacodes** [comment]
Hi @GzimAsani , 

Thank you for your feedback! 🙏 

- [ ] I believe the list of transactions (in my case expenses) is already ordered, with the last recent showing on top. Kindly consider the code from my controller:

Screen Shot 2022-04-20 at 11 31 50

- [ ] The total amount for the category (sum of all of the amounts of the transactions in that category) is displayed at the top of the page:

Screen Shot 2022-04-20 at 11 35 29

- [ ] I have now fixed the devise notifications:

Screen Shot 2022-04-20 at 14 39 47

Screen Shot 2022-04-20 at 14 49 13

- [ ] The tests are running fine for me, both when just running rspec and when running rspec/spec/feature/expense_index_spec.rb. Do you know why this could be and what I could do to fix it?

Running `rspec`: 
Screen Shot 2022-04-20 at 14 43 03

Running `rspec/spec/feature/expense_index_spec.rb`:
Screen Shot 2022-04-20 at 14 47 12

**Comment by GzimAsani** [comment]
> Hi @GzimAsani ,
> 
> Thank you for your feedback! pray
> 
> * [ ]  I believe the list of transactions (in my case expenses) is already ordered, with the last recent showing on top. Kindly consider the code from my controller:
> 
> Screen Shot 2022-04-20 at 11 31 50
> 
> * [ ]  The total amount for the category (sum of all of the amounts of the transactions in that category) is displayed at the top of the page:
> 
> Screen Shot 2022-04-20 at 11 35 29
> 
> * [ ]  I have now fixed the devise notifications:
> 
> Screen Shot 2022-04-20 at 14 39 47
> 
> Screen Shot 2022-04-20 at 14 49 13
> 
> * [ ]  The tests are running fine for me, both when just running rspec and when running rspec/spec/feature/expense_index_spec.rb. Do you know why this could be and what I could do to fix it?
> 
> Running `rspec`: Screen Shot 2022-04-20 at 14 43 03
> 
> Running `rspec/spec/feature/expense_index_spec.rb`: Screen Shot 2022-04-20 at 14 47 12

Hi @Anjacodes,

For some reason they were 2 tests failing on my side, and also the total amount of expenses was not showing on the top of the page. It could be some problem for me locally so if they are working fine on your side, kindly ask for another code review.

**Comment by Anjacodes** [comment]
Hi @GzimAsani, 

Thank you for the prompt reply! How strange that you're seeing something different. This morning my partner opened the app with Safari and I almost had a heart attack because it looked nothing like what it looks like on my screen 😆
I have requested another review but thank you again for your kind and prompt response!

**Comment by GzimAsani** [comment]
Hi @Anjacodes,
I know it happened to me before as well. I do apologize for any confusion caused :pray:

**Review by ahmetbozaci — CHANGES_REQUESTED** [review]
# STATUS: Changes Required  ♻️


@Anjacodes ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___
### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ]As the last reviewer said total expenses are zero and cant see expenses that ı create. The total is shown on the category page, but not on the expenses page. Also, that's why 2 RSpec tests are not passing. Please fix it.
image

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ]  I write them as an optional but this is a requirement that was not mentioned before. I suggest fixing it.

- [ ] After signup, I should see the category page instead of the user page.
image

- [ ] I can see other users’ categories, and expenses if ı create a new user. Every user should sees their own category and expenses.
image
- [ ] Please fix the broken link in the license section of the readme file. Also, you should add [Creative Commons license](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=The%20Creative%20Commons%20license%20of%20the%20design%20requires%20that%20you%20give%20appropriate%20credit%20to%20the%20author.%20Therefore%2C%20you%20must%20do%20it%20in%20the%20README%20of%20your%20project.)
___

### Cheers and Happy coding! 💻 👏

almost

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by ahmetbozaci** [comment]
@Anjacodes  Please also delete node_modules folder in your main branch. Next, TSE can review easily.

**Comment by Anjacodes** [comment]
Hey @ahmetbozaci, 
Thank you for your feedback!
I have removed the node_modules folder from both the main and dev branch but the "Files Changed" still show 5000+ files. I'm so sorry about that 🙈 I promise to be more mindful of the node_modules in my next PR.

For now, I have implemented all the required changes - all my tests are passing on my end and the total expense is being displayed both on the categories index page as well as on the expenses index page.
I have also implemented the following optional changes: 

- [ ] Changed my categories controller so that every user can only see the categories they created
- [ ] I have given credit for the original web design under Acknowledgements

Screen Shot 2022-04-20 at 18 51 55

- [ ] Fixed the broken MIT License Link

**Comment by er-contreras** [comment]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

almost there

 ## Highlights


 ## Required Changes ♻️

- [ ] Here you put as expected "/expenses.4" and you got "/categories/4/expenses". Please check which path are you taking in order to get the correct one.

Screen Shot 2022-04-20 at 20 18 18

- [ ] You have 10 failures with path problems. Please take a look.

Screen Shot 2022-04-20 at 20 28 08

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Anjacodes** [comment]
Hi @eri8-9, 

Thank you for your feedback!
Wow, what a confusion! When I removed the node_modules from main, it resulted in a merge conflict, and when I fixed the conflict, I created a new branch named remove_node-modules, which is the one we are now on but when I made changes I kept pushing to dev, which is why the tests were still not running. 🤯 I really keep my fingers crossed that everything is working as expected now! I merged dev back into remove_node-modules and then pushed again. When I run the test, they all pass and when I check the server on this branch it all seems to be working as expected. Fingers crossed 🤞 Thank you all for your efforts and feedback and sorry about all the back and forth!

**Review by Meltrust — APPROVED** [review]
Hi @Anjacodes,


## Wow, you did it 🎉
## Great work @Anjacodes !
Brilliant
## Thank you for deleting your node_modules folder, and correcting your tests, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
